### ISSUE TITLE
Add feature to backup wiki on the Azure DevOps projects

### ISSUE THREAD

**Issue by sorrentinov** [lionelpere/azure-devops-repository-backup#6]
Hi,

Could be useful to your project also to add a new feature to backup the Wiki of the projects.
In Azure DevOps the project wiki is itself a repo, so I've implemented a change to add:
- a new flag **projectwiki** (if true export also the wiki repo on the projects)
- a backup structure (Eg. backup_data/repo and backup_data/wiki)

Let me know if I can contribute on the project, or creating a new branch 

Regards
Vincenzo

**Comment by lionelpere** [comment]
Feel free to contribute trough a pull request.

I’ll be happy to validate it.

Kind regards,

Lionel
